name: crypto_coins_backend
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.2
  postgres: ^3.5.6
  talker: ^4.7.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
