// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXiCEmwlOKjPYpHGgppHINwlCz16ZEpD0',
    appId: '1:761171946873:web:81e8c9808f8e21922413a8',
    messagingSenderId: '761171946873',
    projectId: 'crypto-list-app-d5a42',
    authDomain: 'crypto-list-app-d5a42.firebaseapp.com',
    storageBucket: 'crypto-list-app-d5a42.firebasestorage.app',
    measurementId: 'G-XV1BTEWZCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnFlBk7lqtibJOjbLUu0cZaEvGVt4uCaM',
    appId: '1:761171946873:android:c68eb91612ba1c442413a8',
    messagingSenderId: '761171946873',
    projectId: 'crypto-list-app-d5a42',
    storageBucket: 'crypto-list-app-d5a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOmPAI2JX0STrARdVwnzoLRgHST7Btkw',
    appId: '1:761171946873:ios:7c273cf57add56db2413a8',
    messagingSenderId: '761171946873',
    projectId: 'crypto-list-app-d5a42',
    storageBucket: 'crypto-list-app-d5a42.firebasestorage.app',
    iosBundleId: 'com.cryptogirl.cryptoCoinsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOmPAI2JX0STrARdVwnzoLRgHST7Btkw',
    appId: '1:761171946873:ios:7c273cf57add56db2413a8',
    messagingSenderId: '761171946873',
    projectId: 'crypto-list-app-d5a42',
    storageBucket: 'crypto-list-app-d5a42.firebasestorage.app',
    iosBundleId: 'com.cryptogirl.cryptoCoinsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXiCEmwlOKjPYpHGgppHINwlCz16ZEpD0',
    appId: '1:761171946873:web:f6cddc0025e5ea2a2413a8',
    messagingSenderId: '761171946873',
    projectId: 'crypto-list-app-d5a42',
    authDomain: 'crypto-list-app-d5a42.firebaseapp.com',
    storageBucket: 'crypto-list-app-d5a42.firebasestorage.app',
    measurementId: 'G-PBB4WP9KQS',
  );
}
